# yaml-language-server: $schema=https://raw.githubusercontent.com/pulumi/pulumi/master/pkg/codegen/schema/pulumi.json
---
name: azure
resources:
  azure:index:AlzArchitecture:
    isComponent: true
    inputProperties:
      architectureName:
        type: string
        description: The name of the ALZ architecture from the library.
      location:
        type: string
        description: The default location of the architecture.
      rootManagementGroupId:
        type: string
        description: The root management group ID.
    requiredInputs:
      - architectureName
      - location
      - rootManagementGroupId
    properties:
      websiteUrl:
        type: string
        description: The website URL.
    required:
      - websiteUrl
language:
  csharp:
    packageReferences:
      Pulumi: 3.*
      Pulumi.AzureNative: 2.*
  go:
    generateResourceContainerTypes: true
    importBasePath: github.com/matt-FFFFFF/pulumi-azure-alz/sdk/go/azure
  nodejs:
    dependencies:
      "@pulumi/azure-native": "^2.0.0"
    devDependencies:
      typescript: "^3.7.0"
  python:
    requires:
      pulumi: ">=3.0.0,<4.0.0"
      pulumi-azure-native: ">=2.0.0,<3.0.0"
