# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .alz_architecture import *
from .provider import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "azure",
  "mod": "index",
  "fqn": "pulumi_azure",
  "classes": {
   "azure:index:AlzArchitecture": "AlzArchitecture"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "azure",
  "token": "pulumi:providers:azure",
  "fqn": "pulumi_azure",
  "class": "Provider"
 }
]
"""
)
