// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class AlzArchitecture extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'azure:index:AlzArchitecture';

    /**
     * Returns true if the given object is an instance of AlzArchitecture.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AlzArchitecture {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AlzArchitecture.__pulumiType;
    }

    /**
     * The website URL.
     */
    public /*out*/ readonly websiteUrl!: pulumi.Output<string>;

    /**
     * Create a AlzArchitecture resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AlzArchitectureArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.architectureName === undefined) && !opts.urn) {
                throw new Error("Missing required property 'architectureName'");
            }
            if ((!args || args.location === undefined) && !opts.urn) {
                throw new Error("Missing required property 'location'");
            }
            if ((!args || args.rootManagementGroupId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'rootManagementGroupId'");
            }
            resourceInputs["architectureName"] = args ? args.architectureName : undefined;
            resourceInputs["location"] = args ? args.location : undefined;
            resourceInputs["rootManagementGroupId"] = args ? args.rootManagementGroupId : undefined;
            resourceInputs["websiteUrl"] = undefined /*out*/;
        } else {
            resourceInputs["websiteUrl"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(AlzArchitecture.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a AlzArchitecture resource.
 */
export interface AlzArchitectureArgs {
    /**
     * The name of the ALZ architecture from the library.
     */
    architectureName: pulumi.Input<string>;
    /**
     * The default location of the architecture.
     */
    location: pulumi.Input<string>;
    /**
     * The root management group ID.
     */
    rootManagementGroupId: pulumi.Input<string>;
}
